# Generated by Django 5.2 on 2025-08-27 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usermanagement.usercategory'),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usermanagement.masterusertype'),
        ),
    ]
